package com.vlad.note.controllers;

import com.vlad.note.domain.User;
import com.vlad.note.repos.UserRepo;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Controller;
import org.springframework.web.bind.annotation.*;

@Controller // This means that this class is a Controller
@RequestMapping(path="/user") // This means URL's start with /demo (after Application path)
public class MainController {
    @Autowired // This means to get the bean called userRepository
    // Which is auto-generated by Spring, we will use it to handle the data
    private UserRepo userRepository;

    @GetMapping(path="/all")
    public @ResponseBody
    Iterable<User> getAllUsers() {
        // This returns a JSON or XML with the users
        return userRepository.findAll();
    }
    @CrossOrigin(origins = "http://localhost:4200")
    @PostMapping(path="/login")
    public @ResponseBody User loginUser(@RequestBody User user) throws Exception{

        User user1=userRepository.findByLogin(user.getLogin());
        if(user1!=null){
            System.out.println("aassssssssssss");
            if(user1.getPassword().equalsIgnoreCase(user.getPassword())){
                return user1;
            }
        }

        throw new Exception("bad request");
    }
    @PostMapping(path = "/logtest")
    public @ResponseBody String loginUser(@RequestBody String user) throws Exception{
    return user;
    }
}
